# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [main]
  pull_request:
    branches : '*'

jobs:
  quality:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x,16.x]
        os: [ubuntu-lates, windows-latest]
          
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test

